/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JFrame;

/**
 *
 * @author Stefanie
 */
public class PainelAdm extends javax.swing.JFrame {

    /**
     * Creates new form PainelAdm
     */
    public PainelAdm() {
        initComponents();
   
        //this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelFundoPainelAdm = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFilme = new javax.swing.JMenu();
        jMenuItemFilmeListar = new javax.swing.JMenuItem();
        jMenuItemFilmeCad = new javax.swing.JMenuItem();
        jMenuItemFilmeAlter = new javax.swing.JMenuItem();
        jMenuUsuario = new javax.swing.JMenu();
        jMenuItemUsuarioCad = new javax.swing.JMenuItem();
        jMenuItemUsuarioAlter = new javax.swing.JMenuItem();
        jMenuGenero = new javax.swing.JMenu();
        jMenuItemGeneroCad = new javax.swing.JMenuItem();
        jMenuItemGeneroAlter = new javax.swing.JMenuItem();
        jMenuEmprestimo = new javax.swing.JMenu();
        jMenuConfiguracoes = new javax.swing.JMenu();
        jMenuItemTelaBemVindo = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabelFundoPainelAdm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fundoPainelAdm.jpg"))); // NOI18N
        getContentPane().add(jLabelFundoPainelAdm);
        jLabelFundoPainelAdm.setBounds(-50, 0, 960, 960);

        jMenuFilme.setText("Filmes");

        jMenuItemFilmeListar.setText("Listar");
        jMenuItemFilmeListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFilmeListarActionPerformed(evt);
            }
        });
        jMenuFilme.add(jMenuItemFilmeListar);

        jMenuItemFilmeCad.setText("Cadastrar");
        jMenuItemFilmeCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFilmeCadActionPerformed(evt);
            }
        });
        jMenuFilme.add(jMenuItemFilmeCad);

        jMenuItemFilmeAlter.setText("Alterar/Excluir");
        jMenuFilme.add(jMenuItemFilmeAlter);

        jMenuBar1.add(jMenuFilme);

        jMenuUsuario.setText("Usuários");

        jMenuItemUsuarioCad.setText("Cadastrar");
        jMenuItemUsuarioCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUsuarioCadActionPerformed(evt);
            }
        });
        jMenuUsuario.add(jMenuItemUsuarioCad);

        jMenuItemUsuarioAlter.setText("Alterar/Excluir");
        jMenuUsuario.add(jMenuItemUsuarioAlter);

        jMenuBar1.add(jMenuUsuario);

        jMenuGenero.setText("Gênero");

        jMenuItemGeneroCad.setText("Cadastrar");
        jMenuGenero.add(jMenuItemGeneroCad);

        jMenuItemGeneroAlter.setText("Alterar/Excluir");
        jMenuGenero.add(jMenuItemGeneroAlter);

        jMenuBar1.add(jMenuGenero);

        jMenuEmprestimo.setText("Empéstimos");
        jMenuBar1.add(jMenuEmprestimo);

        jMenuConfiguracoes.setText("Configurações");

        jMenuItemTelaBemVindo.setText("Tela Bem-Vindo");
        jMenuConfiguracoes.add(jMenuItemTelaBemVindo);

        jMenuBar1.add(jMenuConfiguracoes);

        jMenu6.setText("Ajuda");
        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(930, 810));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemFilmeCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFilmeCadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemFilmeCadActionPerformed

    private void jMenuItemFilmeListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFilmeListarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemFilmeListarActionPerformed

    private void jMenuItemUsuarioCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUsuarioCadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemUsuarioCadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PainelAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PainelAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PainelAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PainelAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PainelAdm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelFundoPainelAdm;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuConfiguracoes;
    private javax.swing.JMenu jMenuEmprestimo;
    private javax.swing.JMenu jMenuFilme;
    private javax.swing.JMenu jMenuGenero;
    private javax.swing.JMenuItem jMenuItemFilmeAlter;
    private javax.swing.JMenuItem jMenuItemFilmeCad;
    private javax.swing.JMenuItem jMenuItemFilmeListar;
    private javax.swing.JMenuItem jMenuItemGeneroAlter;
    private javax.swing.JMenuItem jMenuItemGeneroCad;
    private javax.swing.JMenuItem jMenuItemTelaBemVindo;
    private javax.swing.JMenuItem jMenuItemUsuarioAlter;
    private javax.swing.JMenuItem jMenuItemUsuarioCad;
    private javax.swing.JMenu jMenuUsuario;
    // End of variables declaration//GEN-END:variables
}
